### ISSUE TITLE
IPが自動取得できない環境で起動処理が終わらない

### ISSUE THREAD

**Issue by habuka036** [axsh/iso-no-wakame#12]
DHCPサーバがない or IP アドレスが取得できない環境で起動した場合、以下の処理で dialog がでるため起動処理が終わらない。

https://github.com/axsh/iso-no-wakame/blob/master/wake-wakame-vdc#L461

回避策として、IP アドレスが取得できない場合はその旨をログインコンソールに出力し wake-wakame-vdc を実行してもらうか、もしくはオートログインする wakame ユーザの .bashrc にて自動実行させるべきか。

**Comment by hansode** [comment]
> wake-wakame-vdc

ウェイク！

**Comment by habuka036** [comment]
そうそう、けして「わけわかめ」ではないです σ^^;

**Comment by habuka036** [comment]
とりあえず DHCP を取得できないときは wake-wakame-vdc を終了するようにした。

**Comment by habuka036** [comment]
DHCP を取得できずに自動セットアップが完了しない場合は、デスクトップに /usr/local/bin/wake-wakame-vdc manual_1box を実行するランチャーを置くようにした。
